name: ppd534

channels:
  - conda-forge

dependencies:
  - beautifulsoup4
  - bokeh
  - cartopy
  - cenpy
  - contextily
  - dill
  - folium
  - geopandas
  - jupyterlab
  - mapclassify
  - openpyxl
  - osmnx
  - pandas
  - pillow
  - pysal
  - python == 3.*
  - rasterio
  - seaborn
  - scikit-learn
  - scipy
  - statsmodels
